# Crawl Data Twitter (X)
The crawling process was done using Tweet-Harvest by Helmi Satria.

https://www.youtube.com/@helmisatria/featured

In [ ]:
#@title Instalasi library

# Import required Python package
!pip install pandas

# Install Node.js (because tweet-harvest built using Node.js)
!sudo apt-get update
!sudo apt-get install -y ca-certificates curl gnupg
!sudo mkdir -p /etc/apt/keyrings
!curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg

!NODE_MAJOR=20 && echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | sudo tee /etc/apt/sources.list.d/nodesource.list

!sudo apt-get update
!sudo apt-get install nodejs -y

!node -v

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Get:1 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease [3,632 B]
Get:2 https://cli.github.com/packages stable InRelease [3,917 B]
Get:3 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ Packages [99.9 kB]
Get:4 http://security.ubuntu.com/ubuntu jammy-security InRelease [129 kB]
Get:5 https://cli.github.com/packages stable/main amd64 Packages [354 B]
Hit:6 http://archive.ubuntu.com/ubuntu jammy InRelease
Get:7 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [128 kB]
Get:8 https://r2u.stat.illinois.edu/ubuntu jammy InRelease [6,555 B]
Get:9 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease [18.1 kB]
Get:10 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [4,046 kB]
Get:11 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [1,307 kB]
Get:12 https://r2u.stat.illinois.edu/ubuntu jammy/main amd64 Packages [3,081 kB]
Get:13 http://security.ubuntu.com/ubuntu jammy-security/restricted amd64 Packages [7,258 kB]
Hit:14 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Get:15 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy/main amd64 Packages [38.6 kB]
Get:16 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [127 kB]
Get:17 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [4,379 kB]
Get:18 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [1,612 kB]
Get:19 http://archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages [7,526 kB]
Get:20 http://archive.ubuntu.com/ubuntu jammy-backports/universe amd64 Packages [35.6 kB]
Get:21 http://archive.ubuntu.com/ubuntu jammy-backports/main amd64 Packages [82.8 kB]
Get:22 https://r2u.stat.illinois.edu/ubuntu jammy/main all Packages [10.4 MB]
Fetched 40.3 MB in 5s (8,555 kB/s)
Reading package lists... Done
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
curl is already the newest version (7.81.0-1ubuntu1.24).
gnupg is already the newest version (2.2.27-3ubuntu2.5).
gnupg set to manually installed.
The following packages will be upgraded:
  ca-certificates
1 upgraded, 0 newly installed, 0 to remove and 61 not upgraded.
Need to get 141 kB of archives.
After this operation, 55.3 kB disk space will be freed.
Get:1 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 ca-certificates all 20260601~22.04.1 [141 kB]
Fetched 141 kB in 0s (3,537 kB/s)
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 78, <> line 1.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin:
(Reading database ... 118243 files and directories currently installed.)
Preparing to unpack .../ca-certificates_20260601~22.04.1_all.deb ...
Unpacking ca-certificates (20260601~22.04.1) over (20240203~22.04.1) ...
Setting up ca-certificates (20260601~22.04.1) ...
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 78.)
debconf: falling back to frontend: Readline
Updating certificates in /etc/ssl/certs...
rehash: warning: skipping ca-certificates.crt,it does not contain exactly one certificate or CRL
14 added, 39 removed; done.
Processing triggers for man-db (2.10.2-1) ...
Processing triggers for ca-certificates (20260601~22.04.1) ...
Updating certificates in /etc/ssl/certs...
0 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...

done.
done.
deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_20.x nodistro main
Hit:1 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease
Get:2 https://deb.nodesource.com/node_20.x nodistro InRelease [12.1 kB]
Hit:3 https://cli.github.com/packages stable InRelease
Get:4 https://deb.nodesource.com/node_20.x nodistro/main amd64 Packages [14.7 kB]
Hit:5 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:6 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:7 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:8 https://r2u.stat.illinois.edu/ubuntu jammy InRelease
Hit:9 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:10 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:11 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Fetched 26.8 kB in 1s (20.4 kB/s)
Reading package lists... Done
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  nodejs
0 upgraded, 1 newly installed, 0 to remove and 61 not upgraded.
Need to get 32.2 MB of archives.
After this operation, 196 MB of additional disk space will be used.
Get:1 https://deb.nodesource.com/node_20.x nodistro/main amd64 nodejs amd64 20.20.2-1nodesource1 [32.2 MB]
Fetched 32.2 MB in 1s (63.9 MB/s)
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 78, <> line 1.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin:
Selecting previously unselected package nodejs.
(Reading database ... 118218 files and directories currently installed.)
Preparing to unpack .../nodejs_20.20.2-1nodesource1_amd64.deb ...
Unpacking nodejs (20.20.2-1nodesource1) ...
Setting up nodejs (20.20.2-1nodesource1) ...
Processing triggers for man-db (2.10.2-1) ...
v20.20.2

In [ ]:
# Install dependency Playwright (WAJIB untuk tweet-harvest di Colab)
!npx playwright install-deps chromium
!npx playwright install chromium

⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙Need to install the following packages:
playwright@1.61.1
Ok to proceed? (y) y

⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏Installing dependencies...
Hit:1 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease
Hit:2 https://deb.nodesource.com/node_20.x nodistro InRelease
Hit:3 https://cli.github.com/packages stable InRelease
Hit:4 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:5 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:6 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:7 https://r2u.stat.illinois.edu/ubuntu jammy InRelease
Hit:8 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:9 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:10 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Reading package lists... Done
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
fonts-liberation is already the newest version (1:1.07.4-11).
libfontconfig1 is already the newest version (2.13.1-4.2ubuntu5).
libxcb1 is already the newest version (1.14-3ubuntu3).
libxcb1 set to manually installed.
libxdamage1 is already the newest version (1:1.1.5-2build2).
libxdamage1 set to manually installed.
libxext6 is already the newest version (2:1.3.4-1build1).
libxfixes3 is already the newest version (1:6.0.0-1).
libxfixes3 set to manually installed.
libxkbcommon0 is already the newest version (1.4.0-1).
libxkbcommon0 set to manually installed.
libxrandr2 is already the newest version (2:1.5.2-1build1).
libxrandr2 set to manually installed.
libasound2 is already the newest version (1.2.6.1-1ubuntu1.1).
libasound2 set to manually installed.
libcairo2 is already the newest version (1.16.0-5ubuntu2.1).
libcairo2 set to manually installed.
libdbus-1-3 is already the newest version (1.12.20-2ubuntu4.1).
libdbus-1-3 set to manually installed.
libdrm2 is already the newest version (2.4.113-2~ubuntu0.22.04.1).
libdrm2 set to manually installed.
libfreetype6 is already the newest version (2.11.1+dfsg-1ubuntu0.3).
libfreetype6 set to manually installed.
libglib2.0-0 is already the newest version (2.72.4-0ubuntu2.9).
libnspr4 is already the newest version (2:4.35-0ubuntu0.22.04.1).
libnspr4 set to manually installed.
libnss3 is already the newest version (2:3.98-0ubuntu0.22.04.3).
libnss3 set to manually installed.
libpango-1.0-0 is already the newest version (1.50.6+ds-2ubuntu1).
libpango-1.0-0 set to manually installed.
libwayland-client0 is already the newest version (1.20.0-1ubuntu0.1).
libwayland-client0 set to manually installed.
libx11-6 is already the newest version (2:1.7.5-1ubuntu0.3).
libx11-6 set to manually installed.
xvfb is already the newest version (2:21.1.4-2ubuntu1.7~22.04.16).
The following additional packages will be installed:
  libatk1.0-data libegl-mesa0 libgl1-mesa-dri libglapi-mesa libglx-mesa0
  xfonts-encodings xfonts-utils
Suggested packages:
  cups-common
Recommended packages:
  fonts-ipafont-mincho fonts-tlwg-loma at-spi2-core libgl1-amber-dri
The following NEW packages will be installed:
  fonts-freefont-ttf fonts-ipafont-gothic fonts-noto-color-emoji
  fonts-tlwg-loma-otf fonts-unifont fonts-wqy-zenhei libatk-bridge2.0-0
  libatk1.0-0 libatk1.0-data libatspi2.0-0 libxcomposite1 xfonts-cyrillic
  xfonts-encodings xfonts-scalable xfonts-utils
The following packages will be upgraded:
  libcups2 libegl-mesa0 libgbm1 libgl1-mesa-dri libglapi-mesa libglx-mesa0
6 upgraded, 15 newly installed, 0 to remove and 55 not upgraded.
Need to get 38.1 MB of archives.
After this operation, 68.7 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy/universe amd64 fonts-ipafont-gothic all 00303-21ubuntu1 [3,513 kB]
Get:2 http://archive.ubuntu.com/ubuntu jammy/main amd64 fonts-freefont-ttf all 20120503-10build1 [2,388 kB]
Get:3 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 fonts-noto-color-emoji all 2.047-0ubuntu0.22.04.1 [10.0 MB]
Get:4 http://archive.ubuntu.com/ubuntu jammy/universe amd64 fonts-tlwg-loma-otf all 1:0.7.3-1 [107 kB]
Get:5 http://archive.ubuntu.com/ubuntu jammy/universe amd64 fonts-unifont all 1:14.0.01-1 [3,551 kB]
Get:6 http://archive.ubuntu.com/ubuntu jammy/universe amd64 fonts-wqy-zenhei all 0.9.45-8 [7,472 kB]
Get:7 http://archive.ubuntu.com/ubuntu jammy/main amd64 libatk1.0-data all 2.36.0-3build1 [2,824 B]
Get:8 http://archive.ubuntu.com/ubuntu jammy/main amd64 libatk1.0-0 amd64 2.36.0-3build1 [51.9 kB]
Get:9 http://archive.ubuntu.com/ubuntu jammy/main amd64 libatspi2.0-0 amd64 2.44.0-3 [80.9 kB]
Get:10 http://archive.ubuntu.com/ubuntu jammy/main amd64 libatk-bridge2.0-0 amd64 2.38.0-3 [66.6 kB]
Get:11 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libcups2 amd64 2.4.1op1-1ubuntu4.21 [266 kB]
Get:12 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libegl-mesa0 amd64 23.2.1-1ubuntu3.1~22.04.4 [118 kB]
Get:13 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libgbm1 amd64 23.2.1-1ubuntu3.1~22.04.4 [33.7 kB]
Get:14 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libgl1-mesa-dri amd64 23.2.1-1ubuntu3.1~22.04.4 [8,860 kB]
Get:15 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libglx-mesa0 amd64 23.2.1-1ubuntu3.1~22.04.4 [158 kB]
Get:16 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libglapi-mesa amd64 23.2.1-1ubuntu3.1~22.04.4 [35.6 kB]
Get:17 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxcomposite1 amd64 1:0.4.5-1build2 [7,192 B]
Get:18 http://archive.ubuntu.com/ubuntu jammy/main amd64 xfonts-encodings all 1:1.0.5-0ubuntu2 [578 kB]
Get:19 http://archive.ubuntu.com/ubuntu jammy/main amd64 xfonts-utils amd64 1:7.7+6build2 [94.6 kB]
Get:20 http://archive.ubuntu.com/ubuntu jammy/universe amd64 xfonts-cyrillic all 1:1.0.5 [386 kB]
Get:21 http://archive.ubuntu.com/ubuntu jammy/main amd64 xfonts-scalable all 1:1.0.3-1.2ubuntu1 [306 kB]
Fetched 38.1 MB in 1s (68.3 MB/s)
Selecting previously unselected package fonts-ipafont-gothic.
(Reading database ... 123581 files and directories currently installed.)
Preparing to unpack .../00-fonts-ipafont-gothic_00303-21ubuntu1_all.deb ...
Unpacking fonts-ipafont-gothic (00303-21ubuntu1) ...
Selecting previously unselected package fonts-freefont-ttf.
Preparing to unpack .../01-fonts-freefont-ttf_20120503-10build1_all.deb ...
Unpacking fonts-freefont-ttf (20120503-10build1) ...
Selecting previously unselected package fonts-noto-color-emoji.
Preparing to unpack .../02-fonts-noto-color-emoji_2.047-0ubuntu0.22.04.1_all.deb ...
Unpacking fonts-noto-color-emoji (2.047-0ubuntu0.22.04.1) ...
Selecting previously unselected package fonts-tlwg-loma-otf.
Preparing to unpack .../03-fonts-tlwg-loma-otf_1%3a0.7.3-1_all.deb ...
Unpacking fonts-tlwg-loma-otf (1:0.7.3-1) ...
Selecting previously unselected package fonts-unifont.
Preparing to unpack .../04-fonts-unifont_1%3a14.0.01-1_all.deb ...
Unpacking fonts-unifont (1:14.0.01-1) ...
Selecting previously unselected package fonts-wqy-zenhei.
Preparing to unpack .../05-fonts-wqy-zenhei_0.9.45-8_all.deb ...
Unpacking fonts-wqy-zenhei (0.9.45-8) ...
Selecting previously unselected package libatk1.0-data.
Preparing to unpack .../06-libatk1.0-data_2.36.0-3build1_all.deb ...
Unpacking libatk1.0-data (2.36.0-3build1) ...
Selecting previously unselected package libatk1.0-0:amd64.
Preparing to unpack .../07-libatk1.0-0_2.36.0-3build1_amd64.deb ...
Unpacking libatk1.0-0:amd64 (2.36.0-3build1) ...
Selecting previously unselected package libatspi2.0-0:amd64.
Preparing to unpack .../08-libatspi2.0-0_2.44.0-3_amd64.deb ...
Unpacking libatspi2.0-0:amd64 (2.44.0-3) ...
Selecting previously unselected package libatk-bridge2.0-0:amd64.
Preparing to unpack .../09-libatk-bridge2.0-0_2.38.0-3_amd64.deb ...
Unpacking libatk-bridge2.0-0:amd64 (2.38.0-3) ...
Preparing to unpack .../10-libcups2_2.4.1op1-1ubuntu4.21_amd64.deb ...
Unpacking libcups2:amd64 (2.4.1op1-1ubuntu4.21) over (2.4.1op1-1ubuntu4.16) ...
Preparing to unpack .../11-libegl-mesa0_23.2.1-1ubuntu3.1~22.04.4_amd64.deb ...
Unpacking libegl-mesa0:amd64 (23.2.1-1ubuntu3.1~22.04.4) over (23.2.1-1ubuntu3.1~22.04.3) ...
Preparing to unpack .../12-libgbm1_23.2.1-1ubuntu3.1~22.04.4_amd64.deb ...
Unpacking libgbm1:amd64 (23.2.1-1ubuntu3.1~22.04.4) over (23.2.1-1ubuntu3.1~22.04.3) ...
Preparing to unpack .../13-libgl1-mesa-dri_23.2.1-1ubuntu3.1~22.04.4_amd64.deb ...
Unpacking libgl1-mesa-dri:amd64 (23.2.1-1ubuntu3.1~22.04.4) over (23.2.1-1ubuntu3.1~22.04.3) ...
Preparing to unpack .../14-libglx-mesa0_23.2.1-1ubuntu3.1~22.04.4_amd64.deb ...
Unpacking libglx-mesa0:amd64 (23.2.1-1ubuntu3.1~22.04.4) over (23.2.1-1ubuntu3.1~22.04.3) ...
Preparing to unpack .../15-libglapi-mesa_23.2.1-1ubuntu3.1~22.04.4_amd64.deb ...
Unpacking libglapi-mesa:amd64 (23.2.1-1ubuntu3.1~22.04.4) over (23.2.1-1ubuntu3.1~22.04.3) ...
Selecting previously unselected package libxcomposite1:amd64.
Preparing to unpack .../16-libxcomposite1_1%3a0.4.5-1build2_amd64.deb ...
Unpacking libxcomposite1:amd64 (1:0.4.5-1build2) ...
Selecting previously unselected package xfonts-encodings.
Preparing to unpack .../17-xfonts-encodings_1%3a1.0.5-0ubuntu2_all.deb ...
Unpacking xfonts-encodings (1:1.0.5-0ubuntu2) ...
Selecting previously unselected package xfonts-utils.
Preparing to unpack .../18-xfonts-utils_1%3a7.7+6build2_amd64.deb ...
Unpacking xfonts-utils (1:7.7+6build2) ...
Selecting previously unselected package xfonts-cyrillic.
Preparing to unpack .../19-xfonts-cyrillic_1%3a1.0.5_all.deb ...
Unpacking xfonts-cyrillic (1:1.0.5) ...
Selecting previously unselected package xfonts-scalable.
Preparing to unpack .../20-xfonts-scalable_1%3a1.0.3-1.2ubuntu1_all.deb ...
Unpacking xfonts-scalable (1:1.0.3-1.2ubuntu1) ...
Setting up libgbm1:amd64 (23.2.1-1ubuntu3.1~22.04.4) ...
Setting up fonts-noto-color-emoji (2.047-0ubuntu0.22.04.1) ...
Setting up fonts-wqy-zenhei (0.9.45-8) ...
Setting up fonts-freefont-ttf (20120503-10build1) ...
Setting up libatspi2.0-0:amd64 (2.44.0-3) ...
Setting up fonts-tlwg-loma-otf (1:0.7.3-1) ...
Setting up xfonts-encodings (1:1.0.5-0ubuntu2) ...
Setting up libglapi-mesa:amd64 (23.2.1-1ubuntu3.1~22.04.4) ...
Setting up libcups2:amd64 (2.4.1op1-1ubuntu4.21) ...
Setting up libatk1.0-data (2.36.0-3build1) ...
Setting up fonts-ipafont-gothic (00303-21ubuntu1) ...
update-alternatives: using /usr/share/fonts/opentype/ipafont-gothic/ipag.ttf to provide /usr/share/fonts/truetype/fonts-japanese-gothic.ttf (fonts-japanese-gothic.ttf) in auto mode
Setting up libatk1.0-0:amd64 (2.36.0-3build1) ...
Setting up libxcomposite1:amd64 (1:0.4.5-1build2) ...
Setting up fonts-unifont (1:14.0.01-1) ...
Setting up libgl1-mesa-dri:amd64 (23.2.1-1ubuntu3.1~22.04.4) ...
Setting up xfonts-utils (1:7.7+6build2) ...
Setting up libatk-bridge2.0-0:amd64 (2.38.0-3) ...
Setting up libegl-mesa0:amd64 (23.2.1-1ubuntu3.1~22.04.4) ...
Setting up xfonts-cyrillic (1:1.0.5) ...
Setting up xfonts-scalable (1:1.0.3-1.2ubuntu1) ...
Setting up libglx-mesa0:amd64 (23.2.1-1ubuntu3.1~22.04.4) ...
Processing triggers for man-db (2.10.2-1) ...
Processing triggers for fontconfig (2.13.1-4.2ubuntu5) ...
Processing triggers for libc-bin (2.35-0ubuntu3.13) ...
/sbin/ldconfig.real: /usr/local/lib/libtbb.so.12 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm_debug.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_5.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libhwloc.so.15 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc_proxy.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_0.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_loader.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero_v2.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libumf.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_opencl.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm.so.1 is not a symbolic link

⠙⠙⠹⠸⠼⠴╔═══════════════════════════════════════════════════════════════════════════════╗
║ WARNING: It looks like you are running 'npx playwright install' without first ║
║ installing your project's dependencies.                                       ║
║                                                                               ║
║ To avoid unexpected behavior, please install your dependencies first, and     ║
║ then run Playwright's install command:                                        ║
║                                                                               ║
║     npm install                                                               ║
║     npx playwright install                                                    ║
║                                                                               ║
║ If your project does not yet depend on Playwright, first install the          ║
║ applicable npm package (most commonly @playwright/test), and                  ║
║ then run Playwright's install command to download the browsers:               ║
║                                                                               ║
║     npm install @playwright/test                                              ║
║     npx playwright install                                                    ║
║                                                                               ║
╚═══════════════════════════════════════════════════════════════════════════════╝
Downloading Chrome for Testing 149.0.7827.55 (playwright chromium v1228) from https://cdn.playwright.dev/builds/cft/149.0.7827.55/linux64/chrome-linux64.zip
177 MiB [] 0% 359.8s177 MiB [] 0% 193.3s177 MiB [] 0% 209.9s177 MiB [] 0% 654.0s177 MiB [] 0% 547.1s177 MiB [] 0% 745.9s177 MiB [] 0% 655.4s177 MiB [] 0% 595.7s177 MiB [] 0% 548.0s177 MiB [] 0% 513.5s177 MiB [] 0% 483.6s177 MiB [] 0% 471.5s177 MiB [] 0% 452.0s177 MiB [] 0% 433.7s177 MiB [] 0% 419.7s177 MiB [] 0% 404.5s177 MiB [] 0% 391.2s177 MiB [] 0% 369.5s177 MiB [] 0% 354.9s177 MiB [] 0% 332.4s177 MiB [] 0% 311.8s177 MiB [] 0% 294.5s177 MiB [] 0% 274.9s177 MiB [] 0% 266.2s177 MiB [] 0% 254.8s177 MiB [] 0% 238.6s177 MiB [] 0% 230.9s177 MiB [] 0% 218.9s177 MiB [] 0% 208.6s177 MiB [] 0% 195.3s177 MiB [] 0% 183.4s177 MiB [] 0% 173.6s177 MiB [] 0% 162.0s177 MiB [] 0% 152.3s177 MiB [] 0% 142.9s177 MiB [] 0% 134.0s177 MiB [] 0% 126.4s177 MiB [] 0% 119.7s177 MiB [] 0% 112.8s177 MiB [] 0% 106.7s177 MiB [] 0% 100.6s177 MiB [] 1% 95.2s177 MiB [] 1% 89.8s177 MiB [] 1% 84.4s177 MiB [] 1% 79.2s177 MiB [] 1% 74.4s177 MiB [] 1% 69.7s177 MiB [] 1% 65.4s177 MiB [] 1% 61.5s177 MiB [] 1% 57.8s177 MiB [] 2% 54.3s177 MiB [] 2% 51.1s177 MiB [] 2% 48.2s177 MiB [] 2% 45.7s177 MiB [] 2% 42.1s177 MiB [] 3% 39.5s177 MiB [] 3% 37.1s177 MiB [] 3% 35.5s177 MiB [] 3% 33.8s177 MiB [] 3% 31.8s177 MiB [] 4% 28.9s177 MiB [] 4% 27.7s177 MiB [] 4% 26.7s177 MiB [] 5% 25.7s177 MiB [] 5% 24.8s177 MiB [] 5% 23.6s177 MiB [] 5% 22.5s177 MiB [] 6% 21.7s177 MiB [] 6% 21.2s177 MiB [] 6% 20.7s177 MiB [] 6% 20.2s177 MiB [] 7% 19.7s177 MiB [] 7% 19.2s177 MiB [] 7% 18.5s177 MiB [] 7% 18.1s177 MiB [] 8% 17.5s177 MiB [] 8% 17.2s177 MiB [] 8% 16.9s177 MiB [] 8% 16.6s177 MiB [] 9% 16.3s177 MiB [] 9% 16.0s177 MiB [] 9% 15.6s177 MiB [] 9% 15.4s177 MiB [] 10% 14.9s177 MiB [] 10% 14.7s177 MiB [] 10% 14.5s177 MiB [] 10% 14.3s177 MiB [] 11% 14.1s177 MiB [] 11% 13.8s177 MiB [] 11% 13.6s177 MiB [] 12% 13.3s177 MiB [] 12% 13.2s177 MiB [] 12% 13.0s177 MiB [] 12% 12.9s177 MiB [] 13% 12.7s177 MiB [] 13% 12.6s177 MiB [] 13% 12.3s177 MiB [] 13% 12.2s177 MiB [] 14% 12.0s177 MiB [] 14% 11.8s177 MiB [] 14% 11.7s177 MiB [] 14% 11.6s177 MiB [] 15% 11.5s177 MiB [] 15% 11.4s177 MiB [] 15% 11.3s177 MiB [] 15% 11.1s177 MiB [] 16% 10.9s177 MiB [] 16% 10.8s177 MiB [] 16% 10.7s177 MiB [] 16% 10.6s177 MiB [] 17% 10.6s177 MiB [] 17% 10.5s177 MiB [] 17% 10.3s177 MiB [] 17% 10.2s177 MiB [] 18% 10.1s177 MiB [] 18% 10.0s177 MiB [] 18% 9.9s177 MiB [] 19% 9.9s177 MiB [] 19% 9.8s177 MiB [] 19% 9.7s177 MiB [] 19% 9.6s177 MiB [] 20% 9.4s177 MiB [] 20% 9.3s177 MiB [] 20% 9.2s177 MiB [] 21% 9.2s177 MiB [] 21% 9.1s177 MiB [] 21% 9.0s177 MiB [] 22% 8.9s177 MiB [] 22% 8.8s177 MiB [] 22% 8.7s177 MiB [] 23% 8.6s177 MiB [] 23% 8.5s177 MiB [] 23% 8.4s177 MiB [] 24% 8.4s177 MiB [] 24% 8.3s177 MiB [] 24% 8.2s177 MiB [] 25% 8.1s177 MiB [] 25% 8.0s177 MiB [] 26% 7.9s177 MiB [] 26% 7.8s177 MiB [] 27% 7.7s177 MiB [] 27% 7.6s177 MiB [] 27% 7.5s177 MiB [] 28% 7.5s177 MiB [] 28% 7.4s177 MiB [] 29% 7.3s177 MiB [] 29% 7.2s177 MiB [] 30% 7.1s177 MiB [] 30% 7.0s177 MiB [] 31% 7.0s177 MiB [] 31% 6.9s177 MiB [] 32% 6.8s177 MiB [] 32% 6.7s177 MiB [] 33% 6.6s177 MiB [] 33% 6.5s177 MiB [] 34% 6.5s177 MiB [] 34% 6.4s177 MiB [] 35% 6.3s177 MiB [] 35% 6.2s177 MiB [] 36% 6.2s177 MiB [] 36% 6.1s177 MiB [] 36% 6.0s177 MiB [] 37% 6.0s177 MiB [] 37% 5.9s177 MiB [] 38% 5.9s177 MiB [] 38% 5.8s177 MiB [] 39% 5.7s177 MiB [] 40% 5.6s177 MiB [] 40% 5.5s177 MiB [] 41% 5.4s177 MiB [] 42% 5.4s177 MiB [] 42% 5.3s177 MiB [] 43% 5.2s177 MiB [] 43% 5.1s177 MiB [] 44% 5.1s177 MiB [] 44% 5.0s177 MiB [] 45% 5.0s177 MiB [] 45% 4.9s177 MiB [] 46% 4.9s177 MiB [] 46% 4.8s177 MiB [] 47% 4.7s177 MiB [] 48% 4.7s177 MiB [] 48% 4.6s177 MiB [] 49% 4.5s177 MiB [] 49% 4.4s177 MiB [] 50% 4.4s177 MiB [] 50% 4.3s177 MiB [] 51% 4.3s177 MiB [] 51% 4.2s177 MiB [] 52% 4.2s177 MiB [] 52% 4.1s177 MiB [] 53% 4.1s177 MiB [] 53% 4.0s177 MiB [] 54% 4.0s177 MiB [] 54% 3.9s177 MiB [] 55% 3.9s177 MiB [] 55% 3.8s177 MiB [] 56% 3.8s177 MiB [] 56% 3.7s177 MiB [] 57% 3.7s177 MiB [] 57% 3.6s177 MiB [] 58% 3.6s177 MiB [] 58% 3.5s177 MiB [] 59% 3.5s177 MiB [] 59% 3.4s177 MiB [] 60% 3.4s177 MiB [] 60% 3.3s177 MiB [] 61% 3.3s177 MiB [] 61% 3.2s177 MiB [] 62% 3.2s177 MiB [] 62% 3.1s177 MiB [] 63% 3.1s177 MiB [] 64% 3.0s177 MiB [] 65% 2.9s177 MiB [] 66% 2.8s177 MiB [] 67% 2.7s177 MiB [] 68% 2.7s177 MiB [] 68% 2.6s177 MiB [] 69% 2.6s177 MiB [] 69% 2.5s177 MiB [] 70% 2.5s177 MiB [] 70% 2.4s177 MiB [] 71% 2.4s177 MiB [] 71% 2.3s177 MiB [] 72% 2.3s177 MiB [] 72% 2.2s177 MiB [] 73% 2.2s177 MiB [] 73% 2.1s177 MiB [] 74% 2.1s177 MiB [] 75% 2.0s177 MiB [] 76% 2.0s177 MiB [] 76% 1.9s177 MiB [] 77% 1.9s177 MiB [] 77% 1.8s177 MiB [] 78% 1.8s177 MiB [] 78% 1.7s177 MiB [] 79% 1.7s177 MiB [] 80% 1.6s177 MiB [] 81% 1.5s177 MiB [] 82% 1.4s177 MiB [] 83% 1.4s177 MiB [] 83% 1.3s177 MiB [] 84% 1.3s177 MiB [] 84% 1.2s177 MiB [] 85% 1.2s177 MiB [] 85% 1.1s177 MiB [] 86% 1.1s177 MiB [] 87% 1.1s177 MiB [] 87% 1.0s177 MiB [] 88% 1.0s177 MiB [] 88% 0.9s177 MiB [] 89% 0.9s177 MiB [] 89% 0.8s177 MiB [] 90% 0.8s177 MiB [] 90% 0.7s177 MiB [] 91% 0.7s177 MiB [] 92% 0.6s177 MiB [] 93% 0.6s177 MiB [] 93% 0.5s177 MiB [] 94% 0.5s177 MiB [] 94% 0.4s177 MiB [] 95% 0.4s177 MiB [] 95% 0.3s177 MiB [] 96% 0.3s177 MiB [] 97% 0.2s177 MiB [] 98% 0.1s177 MiB [] 99% 0.1s177 MiB [] 99% 0.0s177 MiB [] 100% 0.0s
Chrome for Testing 149.0.7827.55 (playwright chromium v1228) downloaded to /root/.cache/ms-playwright/chromium-1228
Downloading FFmpeg (playwright ffmpeg v1011) from https://cdn.playwright.dev/dbazure/download/playwright/builds/ffmpeg/1011/ffmpeg-linux.zip
2.3 MiB [] 0% 0.0s2.3 MiB [] 1% 2.1s2.3 MiB [] 4% 1.3s2.3 MiB [] 5% 1.4s2.3 MiB [] 9% 0.9s2.3 MiB [] 12% 0.9s2.3 MiB [] 19% 0.6s2.3 MiB [] 26% 0.4s2.3 MiB [] 39% 0.3s2.3 MiB [] 54% 0.2s2.3 MiB [] 77% 0.1s2.3 MiB [] 100% 0.0s
FFmpeg (playwright ffmpeg v1011) downloaded to /root/.cache/ms-playwright/ffmpeg-1011

In [ ]:
#@title Twitter Auth Token

twitter_auth_token = 'f9303a0b9e146bcf50270d859db45a1949c9af13' #masukkan auth_token twitter

# cara mendapatkan auth_token twitten
# 1. Buka X.com dan klik kanan
# 2. Klik inspect
# 3. Pilih bagian application
# 4. Klik auth_token dan copas auth_tokennya

In [ ]:
#@title Crawl Data

filename = 'dataset_kdrt.csv' # nama file
search_keyword = 'kdrt lang:id'
limit = 100 # jumlah tweet yang ingin didapat

!npx -y tweet-harvest@2.6.1 -o "{filename}" -s "{search_keyword}" --tab "LATEST" -l {limit} --token {twitter_auth_token}

⠙⠹⠸⠼⠴Tweet Harvest [v2.6.1]

Research by Helmi Satria
Use it for Educational Purposes only!

This script uses Chromium Browser to crawl data from Twitter with your Twitter auth token.
Please enter your Twitter auth token when prompted.

Note: Keep your access token secret! Don't share it with anyone else.
Note: This script only runs on your local device.


Opening twitter search page...


Found existing file ./tweets-data/dataset_kdrt_antiKorban.csv, renaming to ./tweets-data/dataset_kdrt_antiKorban.old.csv

Filling in keywords: kdrt lang:id


-- Scrolling... (1) (2) (3) (4)

Your tweets saved to: /content/tweets-data/dataset_kdrt_antiKorban.csv
Total tweets saved: 20


Your tweets saved to: /content/tweets-data/dataset_kdrt_antiKorban.csv
Total tweets saved: 40


Your tweets saved to: /content/tweets-data/dataset_kdrt_antiKorban.csv
Total tweets saved: 60

-- Scrolling... (1) (2)

Your tweets saved to: /content/tweets-data/dataset_kdrt_antiKorban.csv
Total tweets saved: 80


Your tweets saved to: /content/tweets-data/dataset_kdrt_antiKorban.csv
Total tweets saved: 100
Got 100 tweets, done scrolling...
⠙

In [ ]:
import pandas as pd

# Specify the path to your CSV file
file_path = f"tweets-data/{filename}"

# Read the CSV file into a pandas DataFrame
df = pd.read_csv(file_path, delimiter=",")

# Display the DataFrame
display(df)

,conversation_id_str,created_at,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username
0,427607317811834880,Mon Jan 27 01:01:43 +0000 2014,0,8.00 Iksan (3) dan Ibunya menjadi korban keker...,427607317811834880,NaN,NaN,in,NaN,0,2,4,https://x.com/undefined/status/427607317811834880,462994803,NaN
1,426708973526323200,Fri Jan 24 13:32:01 +0000 2014,0,Baca juga: Bagaimana Jika Korban KDRT Tidak Ma...,426708973526323200,NaN,NaN,in,NaN,0,0,2,https://x.com/undefined/status/426708973526323200,81066525,NaN
2,426708871797694465,Fri Jan 24 13:31:37 +0000 2014,1,Baca juga: Berapa Lama Hukuman Penjara untuk P...,426708871797694465,NaN,NaN,in,NaN,0,1,3,https://x.com/undefined/status/426708871797694465,81066525,NaN
3,426383993697599488,Thu Jan 23 16:00:40 +0000 2014,1,Roby Tremonti bantah lakukan KDRT kepada manta...,426383993697599488,NaN,NaN,in,NaN,0,0,2,https://x.com/undefined/status/426383993697599488,41730943,NaN
4,426352757914607616,Thu Jan 23 13:56:33 +0000 2014,0,KDRT!!! /Lapor kak seto/? @minahwwrr: monyong ...,426352757914607616,NaN,NaN,in,NaN,0,1,0,https://x.com/undefined/status/426352757914607616,1967021779,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,400779550121947136,Thu Nov 14 00:17:45 +0000 2013,0,Kasus KDRT Mantan Suami Cornelia Agatha Menola...,400779550121947136,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/400779550121947136,95854816,NaN
96,400637408695156736,Wed Nov 13 14:52:56 +0000 2013,1,Kasus KDRT P21 Mantan Suami Cornelia Agatha Sa...,400637408695156736,NaN,NaN,in,NaN,0,1,12,https://x.com/undefined/status/400637408695156736,69183155,NaN
97,400593899539816448,Wed Nov 13 12:00:02 +0000 2013,0,Kasus KDRT P21 Mantan Suami Cornelia Agatha Sa...,400593899539816448,NaN,NaN,in,NaN,0,0,3,https://x.com/undefined/status/400593899539816448,137282671,NaN
98,400585851828068352,Wed Nov 13 11:28:04 +0000 2013,0,Kasus KDRT Mantan Suami Cornelia Agatha Bisa D...,400585851828068352,NaN,NaN,in,NaN,0,1,0,https://x.com/undefined/status/400585851828068352,47596019,NaN
99,399827593525870594,Mon Nov 11 09:15:01 +0000 2013,1,Di wilayah domestik suami/istri yang merasa be...,399827593525870594,NaN,NaN,in,NaN,0,0,4,https://x.com/undefined/status/399827593525870594,108375032,NaN

In [ ]:
# Cek jumlah data yang didapatkan

num_tweets = len(df)
print(f"Jumlah tweet dalam dataframe adalah {num_tweets}.")

Jumlah tweet dalam dataframe adalah 100.

In [ ]:
df.to_csv('kdrt_antiKorban.csv', index=False)

In [ ]:
df2.head()

,conversation_id_str,created_at,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username
0,1888796814738075737,Mon Feb 10 07:20:48 +0000 2025,1,@ken_fullmetal @rommorningstar @mayyypham @vng...,1888850590845092240,NaN,ken_fullmetal,in,id,0,1,0,https://x.com/0xYogaA/status/1888850590845092240,1583450902341758979,0xYogaA
1,1888576482685116721,Mon Feb 10 06:10:22 +0000 2025,0,@zachsilver16 @dckyy_mw @itstime4changed @your...,1888832865573712091,NaN,zachsilver16,in,NaN,0,0,0,https://x.com/GAdiwansyah/status/1888832865573...,1077306751156772864,GAdiwansyah
2,1888751710577025168,Mon Feb 10 00:47:53 +0000 2025,1,Ada cewe jepang nikah sama cowo irlandia tingg...,1888751710577025168,NaN,NaN,in,On edge,0,0,0,https://x.com/tantan__1go1e/status/18887517105...,131057239,tantan__1go1e
3,1888623007339630784,Sun Feb 09 18:20:57 +0000 2025,0,@Azer11124 berarti kasus kdrt di perempuan leb...,1888654334554259474,NaN,Azer11124,in,NaN,0,0,0,https://x.com/bojackkz/status/1888654334554259474,1662911632509665280,bojackkz
4,1888238506302193755,Sun Feb 09 15:24:19 +0000 2025,4,@abd69650 @apapeduliku313 @kegblgnunfaedh Lapo...,1888609883194286132,NaN,abd69650,in,NaN,0,0,0,https://x.com/wisnu3ds/status/1888609883194286132,1152598196,wisnu3ds

In [ ]:
df2.tail()

,conversation_id_str,created_at,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username
637,1741773739216474618,Mon Jan 01 14:33:22 +0000 2024,1,@jujukyng Itu cewe selingkuhan mungkin korban ...,1741829973927973231,NaN,jujukyng,in,Milan,0,0,0,https://x.com/adefai7/status/1741829973927973231,1355107344716185602,adefai7
638,1741798165718913354,Mon Jan 01 12:26:58 +0000 2024,0,Org org indo kalau nanganin per ngeweeean cepe...,1741798165718913354,NaN,NaN,in,NaN,0,0,0,https://x.com/kangeskopii/status/1741798165718...,4509955819,kangeskopii
639,1741616369962270745,Mon Jan 01 12:04:55 +0000 2024,3,@330Thunderbird @xojolx @Beritasatu Istrinya s...,1741792615610376200,NaN,330Thunderbird,in,NaN,2,1,0,https://x.com/YQianzi68348/status/174179261561...,1656462280148799488,YQianzi68348
640,1741731356756086805,Mon Jan 01 08:01:29 +0000 2024,1,Video Diduga Anggota BNN Aniaya Istri Viral di...,1741731356756086805,NaN,NaN,in,NaN,0,0,0,https://x.com/Alurinfo_Ind/status/174173135675...,1702377197938589696,Alurinfo_Ind
641,1741719013582082444,Mon Jan 01 07:41:06 +0000 2024,0,Jadi gimana cara menjadi tetangga yang baik ke...,1741726226883252728,NaN,txtdariburu,in,"Buru, Indonesia",0,0,0,https://x.com/txtdariburu/status/1741726226883...,1740926759380594688,txtdariburu

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 539 entries, 0 to 538
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   conversation_id_str      539 non-null    int64
 1   created_at               539 non-null    object
 2   favorite_count           539 non-null    int64
 3   full_text                539 non-null    object
 4   id_str                   539 non-null    int64
 5   image_url                169 non-null    object
 6   in_reply_to_screen_name  83 non-null     object
 7   lang                     539 non-null    object
 8   location                 391 non-null    object
 9   quote_count              539 non-null    int64
 10  reply_count              539 non-null    int64
 11  retweet_count            539 non-null    int64
 12  tweet_url                539 non-null    object
 13  user_id_str              539 non-null    int64
 14  username                 539 non-null    object
dtypes: int64(7), object(8)
memory usage: 63.3+ KB

In [ ]:
# Memeriksa apakah ada nilai NaN dalam kolom 'full_text'
nan_rows = df[df['full_text'].isna()]
print("Baris dengan nilai NaN di kolom 'full_text':\n", nan_rows)

Baris dengan nilai NaN di kolom 'full_text':
 Empty DataFrame
Columns: [conversation_id_str, created_at, favorite_count, full_text, id_str, image_url, in_reply_to_screen_name, lang, location, quote_count, reply_count, retweet_count, tweet_url, user_id_str, username]
Index: []

In [ ]:
# Memeriksa duplikat berdasarkan kolom 'full_text'
duplicates = df[df.duplicated(subset=['full_text'], keep=False)]
print("Duplikat berdasarkan 'full_text':\n", duplicates)

Duplikat berdasarkan 'full_text':
      conversation_id_str                      created_at  favorite_count  \
207  1358742526375522309  Mon Feb 08 12:17:58 +0000 2021               0
208  1358751893275762694  Mon Feb 08 12:17:50 +0000 2021               0
209  1358742526375522309  Mon Feb 08 12:16:47 +0000 2021               0
210  1358751592498008067  Mon Feb 08 12:16:38 +0000 2021               0
404   456651626678190080  Thu Apr 17 04:33:26 +0000 2014               0
405   446195966438162433  Wed Mar 19 08:06:22 +0000 2014               0
516   104855569097179136  Sat Aug 20 10:01:30 +0000 2011               0
517   104851795167285250  Sat Aug 20 09:46:30 +0000 2011               0
518   104848697375993856  Sat Aug 20 09:34:12 +0000 2011               0
521   104847513391083520  Sat Aug 20 09:29:29 +0000 2011               0
522   104847428469010432  Sat Aug 20 09:29:09 +0000 2011               0
528    45880067326353408  Thu Mar 10 16:13:55 +0000 2011               0
530    45867604023328768  Thu Mar 10 15:24:23 +0000 2011               0

                                             full_text               id_str  \
207  @restulungagung Stop Kekerasan Dalam Rumah Tan...  1358751927736147968
208  Stop Kekerasan Dalam Rumah Tangga (KDRT) #Stop...  1358751893275762694
209  @restulungagung Stop Kekerasan Dalam Rumah Tan...  1358751629235879944
210  Stop Kekerasan Dalam Rumah Tangga (KDRT) #Stop...  1358751592498008067
404  Jauh sebelum HAM berdiri Islam sudah mewanti-w...   456651626678190080
405  Jauh sebelum HAM berdiri Islam sudah mewanti-w...   446195966438162433
516  RT @PelajarKocak: Biarpun elu drummer bukan be...   104855569097179136
517  RT @PelajarKocak: Biarpun elu drummer bukan be...   104851795167285250
518  RT @PelajarKocak: Biarpun elu drummer bukan be...   104848697375993856
521  RT @PelajarKocak: Biarpun elu drummer bukan be...   104847513391083520
522  RT @PelajarKocak: Biarpun elu drummer bukan be...   104847428469010432
528  RT @ameronsiahaan: +10juta! RT @LeoSimorangkir...    45880067326353408
530  RT @ameronsiahaan: +10juta! RT @LeoSimorangkir...    45867604023328768

                                           image_url in_reply_to_screen_name  \
207                                              NaN              1Maha_Sena
208                                              NaN                     NaN
209                                              NaN              1Maha_Sena
210                                              NaN                     NaN
404  https://pbs.twimg.com/media/BisrupbCQAA9P_V.jpg                     NaN
405  https://pbs.twimg.com/media/BisrupbCQAA9P_V.jpg                     NaN
516                                              NaN                     NaN
517                                              NaN                     NaN
518                                              NaN                     NaN
521                                              NaN                     NaN
522                                              NaN                     NaN
528                                              NaN                     NaN
530                                              NaN                     NaN

    lang                    location  quote_count  reply_count  retweet_count  \
207   in                         NaN            0            0              0
208   in                         NaN            0            0              0
209   in        Kalidawir, Indonesia            0            0              0
210   in        Kalidawir, Indonesia            0            0              0
404   in    Dibelakang resi JNE ˆ⌣ˆ             0            0              0
405   in    Dibelakang resi JNE ˆ⌣ˆ             0            0              0
516   in  ÜT: -5.1451052,119.4555504            0            0              0
517   in                         NaN            0            0              0
518   in                    Surabaya            0            0              0
521   in                         NaN            0            0              0
522   in                         NaN            0            0              0
528   in                         NaN            0            0              0
530   in      Jakarta Capital Region            0            0              0

                                             tweet_url          user_id_str  \
207  https://x.com/KenArok4444/status/1358751927736...  1315479863415848960
208  https://x.com/KenArok4444/status/1358751893275...  1315479863415848960
209  https://x.com/TongBaj18182097/status/135875162...  1315475560621985792
210  https://x.com/TongBaj18182097/status/135875159...  1315475560621985792
404  https://x.com/JuraganBukuID/status/45665162667...           1058053782
405  https://x.com/JuraganBukuID/status/44619596643...           1058053782
516  https://x.com/chiellokrisna/status/10485556909...            226524862
517  https://x.com/Hezron_priana/status/10485179516...            262573800
518  https://x.com/carelezzkid/status/1048486973759...            224952632
521  https://x.com/FirliyahR/status/104847513391083520            304845089
522  https://x.com/fifi_laugh/status/10484742846901...            130048520
528  https://x.com/ms_sitindjak/status/458800673263...            241652755
530      https://x.com/ryndes/status/45867604023328768             41525123

            username
207      KenArok4444
208      KenArok4444
209  TongBaj18182097
210  TongBaj18182097
404    JuraganBukuID
405    JuraganBukuID
516    chiellokrisna
517    Hezron_priana
518      carelezzkid
521        FirliyahR
522       fifi_laugh
528     ms_sitindjak
530           ryndes

In [ ]:
# Menghapus baris duplikat berdasarkan kolom 'full_text'
df_cleaned = df.drop_duplicates(subset=['full_text'])

In [ ]:
# Memeriksa duplikat berdasarkan kolom 'full_text'
duplicates = df_cleaned[df_cleaned.duplicated(subset=['full_text'], keep=False)]
print("Duplikat berdasarkan 'full_text':\n", duplicates)

Duplikat berdasarkan 'full_text':
 Empty DataFrame
Columns: [conversation_id_str, created_at, favorite_count, full_text, id_str, image_url, in_reply_to_screen_name, lang, location, quote_count, reply_count, retweet_count, tweet_url, user_id_str, username]
Index: []

In [ ]:
#  save file to csv

# Assuming df_cleaned is the DataFrame you want to save
df_cleaned.to_csv('cleaned_kdrtBillar.csv', index=False)

In [ ]:
df_cleaned.tail()

,conversation_id_str,created_at,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username
3072,1852394070376886360,Fri Nov 01 17:36:50 +0000 2024,0,@mekbdi Ky abis di kdrt by,1852404446330007901,NaN,mekbdi,in,Aerendale,0,1,0,https://x.com/akumagrrr/status/185240444633000...,1539515263061700608,akumagrrr
3073,1852400803954479506,Fri Nov 01 17:22:22 +0000 2024,0,kangennn goldie si anak kdrt,1852400803954479506,NaN,NaN,in,NaN,0,0,0,https://x.com/LEECHANY0UNG/status/185240080395...,1495295794366541824,LEECHANY0UNG
3074,1852384752776393073,Fri Nov 01 17:02:33 +0000 2024,0,Belum lagi klo dapet laki yg tempramental Ga c...,1852395817233199330,NaN,joanna_wegner1,in,NaN,0,0,0,https://x.com/joanna_wegner1/status/1852395817...,1590293509948329984,joanna_wegner1
3075,1852387958734959034,Fri Nov 01 16:31:19 +0000 2024,1,kesel bngt klo baca cerita istri /seorang ibu ...,1852387958734959034,NaN,NaN,in,She/her,0,0,0,https://x.com/lyney4me/status/1852387958734959034,1726153573652967424,lyney4me
3076,1852378500948234691,Fri Nov 01 16:12:18 +0000 2024,0,@KATHYYgr kak... gabole kdrt,1852383170189996283,NaN,nayanikareinn,in,snd,0,0,0,https://x.com/aeningyh/status/1852383170189996283,1826507667697008642,aeningyh

In [ ]:
df_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 539 entries, 0 to 538
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   full_text  539 non-null    object
 1   username   539 non-null    object
dtypes: object(2)
memory usage: 8.6+ KB

In [ ]:
#  drop semua kolom kecuali full_text dan username pada df_cleaned

df_cleaned = df[['full_text', 'username']]

In [ ]:
df_cleaned.to_csv("stopkdrt_bersih.csv")

In [ ]:
#  drop semua kolom kecuali full_text dan username pada df_cleaned

df2 = df_cleaned[['full_text', 'username']]

In [ ]:
df1 = pd.read_excel('kdrt1_blmbersih.xlsx')

In [ ]:
df1.head()

                                           full_text    username
0                      @isbellaruby @ycbennette kdrt  prengutJJH
1  Menikah adalah hal yang baik. Konsekuensinya a...  ruangtahul
2  @SitiMelyanaaa pelaku kdrt ini keknya bisa dip...   XANOSHITA
3  @ngemtot @iamoneofwan Solusi tolol! Pantesan l...   ShinFa_04
4  @ngemtot Sewajarnya itu ambigu loh bocil norma...   ShinFa_04

In [ ]:
df2.head()

                                           full_text       username
0  @ken_fullmetal @rommorningstar @mayyypham @vng...        0xYogaA
1  @zachsilver16 @dckyy_mw @itstime4changed @your...    GAdiwansyah
2  Ada cewe jepang nikah sama cowo irlandia tingg...  tantan__1go1e
3  @Azer11124 berarti kasus kdrt di perempuan leb...       bojackkz
4  @abd69650 @apapeduliku313 @kegblgnunfaedh Lapo...       wisnu3ds

In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3077 entries, 0 to 3076
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   full_text  3070 non-null   object
 1   username   3077 non-null   object
dtypes: object(2)
memory usage: 48.2+ KB

In [ ]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 641 entries, 0 to 640
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   full_text  641 non-null    object
 1   username   641 non-null    object
dtypes: object(2)
memory usage: 15.0+ KB

In [ ]:
#  gabungkan data df1 dan df2 ke df baru

# Gabungkan df1 dan df2 menjadi df_baru
df_baru = pd.concat([df1, df2], ignore_index=True)

# Tampilkan beberapa baris pertama dari df_baru
df_baru.head()

                                           full_text    username
0                      @isbellaruby @ycbennette kdrt  prengutJJH
1  Menikah adalah hal yang baik. Konsekuensinya a...  ruangtahul
2  @SitiMelyanaaa pelaku kdrt ini keknya bisa dip...   XANOSHITA
3  @ngemtot @iamoneofwan Solusi tolol! Pantesan l...   ShinFa_04
4  @ngemtot Sewajarnya itu ambigu loh bocil norma...   ShinFa_04

In [ ]:
df_baru.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3718 entries, 0 to 3717
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   full_text  3711 non-null   object
 1   username   3718 non-null   object
dtypes: object(2)
memory usage: 58.2+ KB

In [ ]:
# Memeriksa apakah ada nilai NaN dalam kolom 'full_text'
nan_rows = df_baru[df_baru['full_text'].isna()]
print("Baris dengan nilai NaN di kolom 'full_text':\n", nan_rows)

Baris dengan nilai NaN di kolom 'full_text':
      full_text        username
117        NaN          exsyvc
462        NaN        dshcubba
1175       NaN  controversweet
2347       NaN        sibcheng
2405       NaN  antipsychaotic
2945       NaN    bakuldimsum_
2983       NaN        238N0ZZA

In [ ]:
df_baru_cleaned = df_baru.dropna(subset=['full_text'])

In [ ]:
# Memeriksa apakah ada nilai NaN dalam kolom 'full_text'
nan_rows = df_baru_cleaned[df_baru_cleaned['full_text'].isna()]
print("Baris dengan nilai NaN di kolom 'full_text':\n", nan_rows)

Baris dengan nilai NaN di kolom 'full_text':
 Empty DataFrame
Columns: [full_text, username]
Index: []

In [ ]:
# Memeriksa duplikat berdasarkan kolom 'full_text'
duplicates = df_baru_cleaned[df_baru_cleaned.duplicated(subset=['full_text'], keep=False)]
print("Duplikat berdasarkan 'full_text':\n", duplicates)

Duplikat berdasarkan 'full_text':
                                               full_text         username
111                                                Kdrt      zaleavarraa
313                                                KDRT         bitolols
328                                                KDRT    lakinyaminami
668                                                Kdrt      juliduakali
927               @tinklesm Kdrt dan selingkuh tentunya     riyansupyans
939               @tinklesm Kdrt dan selingkuh tentunya          threags
954   GUYS TOLONG AKUUUU aku mau ngelaporin kaka ipa...    makanapayaena
1124            @Sooyawng KDRT KAMU AK LAPOR PULICI LOH      JIMlNXJAMIE
1191  @PallakaGO @DS_yantie Lapor sih bisa cuma ngga...     suprayitno_r
1383                                               kdrt     adalahpasien
1396                                               Kdrt    Rainydayinyou
1773  Btw buat kalian yang sering kena KDRT apalagi ...        b0balatte
1992  Lu pancing bapak laknat lu itu biar keluar rum...    LovableYoonJi
2017  @buruburu012 @larassdwiw Tu dia pernah nemu ka...      nissa_cimay
2034  @QuoteAja Ini kam mba nya merasa dirinya terga...          AwtPrnm
2076             @_AbundantPeace Aku lapor polisi KDRT.        oksit0sin
2102                                               kdrt  GlacerCHAEYOUNG
2121                                               kdrt        SKLAZZOFC
2236  Deket pasar langganan mama lagi rame gegara ad...       Mahisaturn
2510  Jadi keingetan soal salah satu rekan kerja lum...       dearkirito
2598  @PartBurungGalak Hrs nya dia lapor kena kasus ...     AliminHerman
2712  @chimonjeandra Ya itu sih karena udah kena man...         WiskasKu
2776  Pemerkosaan pelecehan seksual pembunuhan pencu...      archive4nad
2826  lapor kena pelecehan di sepelein lapor kehilan...           yaxtim
2929  @ubel_bluebell Udh ketebak sih siapa pelaku pe...  rizky_maulida19
3061  @Metro_TV Nah udah paling bener ini nerima sis...       pandAE86__
3156  GUYS TOLONG AKUUUU aku mau ngelaporin kaka ipa...    makanapayaena
3157            @Sooyawng KDRT KAMU AK LAPOR PULICI LOH      JIMlNXJAMIE
3159  @PallakaGO @DS_yantie Lapor sih bisa cuma ngga...     suprayitno_r
3165  Btw buat kalian yang sering kena KDRT apalagi ...        b0balatte
3167  Lu pancing bapak laknat lu itu biar keluar rum...    LovableYoonJi
3169  @buruburu012 @larassdwiw Tu dia pernah nemu ka...      nissa_cimay
3170  @QuoteAja Ini kam mba nya merasa dirinya terga...          AwtPrnm
3173             @_AbundantPeace Aku lapor polisi KDRT.        oksit0sin
3174  Deket pasar langganan mama lagi rame gegara ad...       Mahisaturn
3176  Jadi keingetan soal salah satu rekan kerja lum...       dearkirito
3178  @PartBurungGalak Hrs nya dia lapor kena kasus ...     AliminHerman
3181  @chimonjeandra Ya itu sih karena udah kena man...         WiskasKu
3182  Pemerkosaan pelecehan seksual pembunuhan pencu...      archive4nad
3183  lapor kena pelecehan di sepelein lapor kehilan...           yaxtim
3185  @ubel_bluebell Udh ketebak sih siapa pelaku pe...  rizky_maulida19
3189  @Metro_TV Nah udah paling bener ini nerima sis...       pandAE86__

In [ ]:
# Menghapus baris duplikat berdasarkan kolom 'full_text'
df_baru_cleaned = df_baru.drop_duplicates(subset=['full_text'])

In [ ]:
df_baru_cleaned.head()

                                           full_text    username
0                      @isbellaruby @ycbennette kdrt  prengutJJH
1  Menikah adalah hal yang baik. Konsekuensinya a...  ruangtahul
2  @SitiMelyanaaa pelaku kdrt ini keknya bisa dip...   XANOSHITA
3  @ngemtot @iamoneofwan Solusi tolol! Pantesan l...   ShinFa_04
4  @ngemtot Sewajarnya itu ambigu loh bocil norma...   ShinFa_04

In [ ]:
df_baru_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3690 entries, 0 to 3717
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   full_text  3689 non-null   object
 1   username   3690 non-null   object
dtypes: object(2)
memory usage: 86.5+ KB

In [ ]:
df_baru_cleaned.to_csv('cleaned_kdrtTotal.csv', index=False)

In [ ]:
df3 = pd.read_csv('kdrt (3).csv')

In [ ]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 972 entries, 0 to 971
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   conversation_id_str      972 non-null    int64
 1   created_at               972 non-null    object
 2   favorite_count           972 non-null    int64
 3   full_text                972 non-null    object
 4   id_str                   972 non-null    int64
 5   image_url                43 non-null     object
 6   in_reply_to_screen_name  643 non-null    object
 7   lang                     972 non-null    object
 8   location                 510 non-null    object
 9   quote_count              972 non-null    int64
 10  reply_count              972 non-null    int64
 11  retweet_count            972 non-null    int64
 12  tweet_url                972 non-null    object
 13  user_id_str              972 non-null    int64
 14  username                 972 non-null    object
dtypes: int64(7), object(8)
memory usage: 114.0+ KB

In [ ]:
# Memeriksa apakah ada nilai NaN dalam kolom 'full_text'
nan_rows = df3[df3['full_text'].isna()]
print("Baris dengan nilai NaN di kolom 'full_text':\n", nan_rows)

Baris dengan nilai NaN di kolom 'full_text':
 Empty DataFrame
Columns: [conversation_id_str, created_at, favorite_count, full_text, id_str, image_url, in_reply_to_screen_name, lang, location, quote_count, reply_count, retweet_count, tweet_url, user_id_str, username]
Index: []

In [ ]:
# Memeriksa duplikat berdasarkan kolom 'full_text'
duplicates = df3[df3.duplicated(subset=['full_text'], keep=False)]
print("Duplikat berdasarkan 'full_text':\n", duplicates)

Duplikat berdasarkan 'full_text':
      conversation_id_str                      created_at  favorite_count  \
359  1823352855342071901  Tue Aug 13 13:36:11 +0000 2024               0
557  1769567701499027957  Mon Mar 18 03:33:11 +0000 2024               0
678  1741964067382948037  Mon Jan 01 23:26:12 +0000 2024               0
684  1741719013582082444  Mon Jan 01 07:41:06 +0000 2024               0
736  1734034289724150145  Mon Dec 11 02:16:06 +0000 2023               0

                                             full_text               id_str  \
359  Jangan Takut Melapor Begini Cara Lapor KDRT On...  1823352855342071901
557  Jangan Takut Melapor Begini Cara Lapor KDRT On...  1769567701499027957
678  Jadi gimana cara menjadi tetangga yang baik ke...  1741964067382948037
684  Jadi gimana cara menjadi tetangga yang baik ke...  1741726226883252728
736  Jangan Takut Melapor Begini Cara Lapor KDRT On...  1734034289724150145

    image_url in_reply_to_screen_name lang         location  quote_count  \
359       NaN                     NaN   in        Indonesia            0
557       NaN                     NaN   in        Indonesia            0
678       NaN                     NaN   in  Buru, Indonesia            0
684       NaN             txtdariburu   in  Buru, Indonesia            0
736       NaN                     NaN   in        Indonesia            0

     reply_count  retweet_count  \
359            0              1
557            0              1
678            0              0
684            0              0
736            0              1

                                             tweet_url          user_id_str  \
359  https://x.com/Popmama_com/status/1823352855342...           2661838418
557  https://x.com/Popmama_com/status/1769567701499...           2661838418
678  https://x.com/txtdariburu/status/1741964067382...  1740926759380594688
684  https://x.com/txtdariburu/status/1741726226883...  1740926759380594688
736  https://x.com/Popmama_com/status/1734034289724...           2661838418

        username
359  Popmama_com
557  Popmama_com
678  txtdariburu
684  txtdariburu
736  Popmama_com

In [ ]:
# Menghapus baris duplikat berdasarkan kolom 'full_text'
df3_cleaned = df3.drop_duplicates(subset=['full_text'])

In [ ]:
# Memeriksa duplikat berdasarkan kolom 'full_text'
duplicates = df3_cleaned[df3_cleaned.duplicated(subset=['full_text'], keep=False)]
print("Duplikat berdasarkan 'full_text':\n", duplicates)

Duplikat berdasarkan 'full_text':
 Empty DataFrame
Columns: [conversation_id_str, created_at, favorite_count, full_text, id_str, image_url, in_reply_to_screen_name, lang, location, quote_count, reply_count, retweet_count, tweet_url, user_id_str, username]
Index: []

In [ ]:
df3_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
Index: 969 entries, 0 to 971
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   conversation_id_str      969 non-null    int64
 1   created_at               969 non-null    object
 2   favorite_count           969 non-null    int64
 3   full_text                969 non-null    object
 4   id_str                   969 non-null    int64
 5   image_url                43 non-null     object
 6   in_reply_to_screen_name  642 non-null    object
 7   lang                     969 non-null    object
 8   location                 507 non-null    object
 9   quote_count              969 non-null    int64
 10  reply_count              969 non-null    int64
 11  retweet_count            969 non-null    int64
 12  tweet_url                969 non-null    object
 13  user_id_str              969 non-null    int64
 14  username                 969 non-null    object
dtypes: int64(7), object(8)
memory usage: 121.1+ KB

In [ ]:
#  drop semua kolom kecuali full_text dan username pada df_cleaned

df3_fix = df3_cleaned[['full_text', 'username']]

In [ ]:
#  gabungkan data df1 dan df2 ke df baru

# Gabungkan df1 dan df2 menjadi df_baru
df_baru2 = pd.concat([df_baru_cleaned, df3_fix], ignore_index=True)

# Tampilkan beberapa baris pertama dari df_baru
df_baru2.head()

                                           full_text    username
0                      @isbellaruby @ycbennette kdrt  prengutJJH
1  Menikah adalah hal yang baik. Konsekuensinya a...  ruangtahul
2  @SitiMelyanaaa pelaku kdrt ini keknya bisa dip...   XANOSHITA
3  @ngemtot @iamoneofwan Solusi tolol! Pantesan l...   ShinFa_04
4  @ngemtot Sewajarnya itu ambigu loh bocil norma...   ShinFa_04

In [ ]:
df_baru2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4659 entries, 0 to 4658
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   full_text  4658 non-null   object
 1   username   4659 non-null   object
dtypes: object(2)
memory usage: 72.9+ KB

In [ ]:
# Memeriksa apakah ada nilai NaN dalam kolom 'full_text'
nan_rows = df_baru2[df_baru2['full_text'].isna()]
print("Baris dengan nilai NaN di kolom 'full_text':\n", nan_rows)

Baris dengan nilai NaN di kolom 'full_text':
     full_text username
117       NaN   exsyvc

In [ ]:
df_total_cleaned = df_baru2.dropna(subset=['full_text'])

In [ ]:
# Memeriksa apakah ada nilai NaN dalam kolom 'full_text'
nan_rows = df_total_cleaned[df_total_cleaned['full_text'].isna()]
print("Baris dengan nilai NaN di kolom 'full_text':\n", nan_rows)

Baris dengan nilai NaN di kolom 'full_text':
 Empty DataFrame
Columns: [full_text, username]
Index: []

In [ ]:
# Memeriksa duplikat berdasarkan kolom 'full_text'
duplicates = df_total_cleaned[df_total_cleaned.duplicated(subset=['full_text'], keep=False)]
print("Duplikat berdasarkan 'full_text':\n", duplicates)

Duplikat berdasarkan 'full_text':
                                               full_text         username
75          @dearchaniee TLONG BNTU LAPOR AKU KENA KDRT       mognahceah
123   Sumpah gue pengen cerita ini bener bener sanga...    Msmoon7343381
258   @ramydhia Biar gueh rangkum keluh kesah orang2...       LittleDucx
318   Ada istri korban kdrt suami lapor polisi sama ...         ireona29
441   TW// KDRT || Bantu Kawal Seorang Dokter di Nga...  bacottetangga__
...                                                 ...              ...
4368  @limeramen @REP0RT_ID Kdrt sama kekerasan buka...        Scopuvier
4369  @jujukyng Itu cewe selingkuhan mungkin korban ...          adefai7
4370  Org org indo kalau nanganin per ngeweeean cepe...      kangeskopii
4371  @330Thunderbird @xojolx @Beritasatu Istrinya s...     YQianzi68348
4372  Video Diduga Anggota BNN Aniaya Istri Viral di...     Alurinfo_Ind

[818 rows x 2 columns]

In [ ]:
# Menghapus baris duplikat berdasarkan kolom 'full_text'
df_total_cleaned = df_total_cleaned.drop_duplicates(subset=['full_text'])

In [ ]:
# Memeriksa duplikat berdasarkan kolom 'full_text'
duplicates = df_total_cleaned[df_total_cleaned.duplicated(subset=['full_text'], keep=False)]
print("Duplikat berdasarkan 'full_text':\n", duplicates)

Duplikat berdasarkan 'full_text':
 Empty DataFrame
Columns: [full_text, username]
Index: []

In [ ]:
df_total_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4249 entries, 0 to 4658
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   full_text  4249 non-null   object
 1   username   4249 non-null   object
dtypes: object(2)
memory usage: 99.6+ KB

In [ ]:
df_total_cleaned.to_csv('cleaned_kdrtTotal2.csv', index=False)

In [ ]:
df4 = pd.read_csv('kdrt (4).csv')

In [ ]:
df4.head()

,conversation_id_str,created_at,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username
0,1893369456664957336,Sat Feb 22 18:37:10 +0000 2025,0,pernah jd korban kdrt haha dipersulit + diulur...,1893369456664957336,NaN,NaN,in,NaN,0,1,0,https://x.com/dadskarma/status/189336945666495...,90573290,dadskarma
1,1893138573978919362,Sat Feb 22 17:11:39 +0000 2025,0,@Heraloebss Temenku bawa 2 batita dianter adek...,1893347936043426191,NaN,Heraloebss,in,"Kota Batam, Kepulauan Riau",0,0,0,https://x.com/aiiDAMN/status/1893347936043426191,414581663,aiiDAMN
2,1893298671497740559,Sat Feb 22 13:55:53 +0000 2025,0,miris bgt yaaaa indon tuh rill ga decent civil...,1893298671497740559,NaN,NaN,in,NaN,0,1,0,https://x.com/ceratoph_/status/189329867149774...,1558970121288564736,ceratoph_
3,1893266054895321376,Sat Feb 22 13:20:04 +0000 2025,0,@geprekalter gue lapor kdrt sendirian ke polse...,1893289655488979009,NaN,geprekalter,in,Indonesia,0,0,0,https://x.com/ch0choyule/status/18932896554889...,1006481777009963008,ch0choyule
4,1893274186266624390,Sat Feb 22 12:18:35 +0000 2025,26,&gt; Dijelasin kalo mau visum ntar prosedurnya...,1893274186266624390,NaN,NaN,in,indonesia,0,1,12,https://x.com/frierensaga/status/1893274186266...,1005123494470869003,frierensaga

In [ ]:
df4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1498 entries, 0 to 1497
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   conversation_id_str      1498 non-null   int64
 1   created_at               1498 non-null   object
 2   favorite_count           1498 non-null   int64
 3   full_text                1498 non-null   object
 4   id_str                   1498 non-null   int64
 5   image_url                77 non-null     object
 6   in_reply_to_screen_name  1009 non-null   object
 7   lang                     1498 non-null   object
 8   location                 805 non-null    object
 9   quote_count              1498 non-null   int64
 10  reply_count              1498 non-null   int64
 11  retweet_count            1498 non-null   int64
 12  tweet_url                1498 non-null   object
 13  user_id_str              1498 non-null   int64
 14  username                 1498 non-null   object
dtypes: int64(7), object(8)
memory usage: 175.7+ KB

In [ ]:
# Memeriksa apakah ada nilai NaN dalam kolom 'full_text'
nan_rows = df4[df4['full_text'].isna()]
print("Baris dengan nilai NaN di kolom 'full_text':\n", nan_rows)

Baris dengan nilai NaN di kolom 'full_text':
 Empty DataFrame
Columns: [conversation_id_str, created_at, favorite_count, full_text, id_str, image_url, in_reply_to_screen_name, lang, location, quote_count, reply_count, retweet_count, tweet_url, user_id_str, username]
Index: []

In [ ]:
# Memeriksa duplikat berdasarkan kolom 'full_text'
duplicates = df4[df4.duplicated(subset=['full_text'], keep=False)]
print("Duplikat berdasarkan 'full_text':\n", duplicates)

Duplikat berdasarkan 'full_text':
       conversation_id_str                      created_at  favorite_count  \
725   1741964067382948037  Mon Jan 01 23:26:12 +0000 2024               0
731   1741719013582082444  Mon Jan 01 07:41:06 +0000 2024               0
801   1734034289724150145  Mon Dec 11 02:16:06 +0000 2023               0
982   1713772293552513093  Mon Oct 16 04:22:09 +0000 2023               0
1141  1701534688123498761  Tue Sep 12 09:54:17 +0000 2023               1
1142  1701534584780083258  Tue Sep 12 09:53:52 +0000 2023               1
1237  1696192993173356786  Tue Aug 29 07:14:57 +0000 2023               1
1238  1696192993173356786  Tue Aug 29 03:25:07 +0000 2023               1

                                              full_text               id_str  \
725   Jadi gimana cara menjadi tetangga yang baik ke...  1741964067382948037
731   Jadi gimana cara menjadi tetangga yang baik ke...  1741726226883252728
801   Jangan Takut Melapor Begini Cara Lapor KDRT On...  1734034289724150145
982   Jangan Takut Melapor Begini Cara Lapor KDRT On...  1713772293552513093
1141  https://t.co/ZqFooAowdk @ahriesonta @ListyoSig...  1701534688123498761
1142  https://t.co/ZqFooAowdk @ahriesonta @ListyoSig...  1701534584780083258
1237                        @BlueHooligan___ Lapor kdrt  1696421162442760380
1238                        @BlueHooligan___ Lapor kdrt  1696363320243363891

     image_url in_reply_to_screen_name lang                    location  \
725        NaN                     NaN   in             Buru, Indonesia
731        NaN             txtdariburu   in             Buru, Indonesia
801        NaN                     NaN   in                   Indonesia
982        NaN                     NaN   in                   Indonesia
1141       NaN                     NaN   in  Kota Medan, Sumatera Utara
1142       NaN                     NaN   in  Kota Medan, Sumatera Utara
1237       NaN         BlueHooligan___   in                         NaN
1238       NaN         BlueHooligan___   in            Chester, England

      quote_count  reply_count  retweet_count  \
725             0            0              0
731             0            0              0
801             0            0              1
982             0            0              0
1141            0            0              1
1142            0            0              1
1237            0            0              0
1238            0            0              0

                                              tweet_url          user_id_str  \
725   https://x.com/txtdariburu/status/1741964067382...  1740926759380594688
731   https://x.com/txtdariburu/status/1741726226883...  1740926759380594688
801   https://x.com/Popmama_com/status/1734034289724...           2661838418
982   https://x.com/Popmama_com/status/1713772293552...           2661838418
1141  https://x.com/PEMERHATIHKMSMT/status/170153468...  1446189896784220167
1142  https://x.com/PEMERHATIHKMSMT/status/170153458...  1446189896784220167
1237    https://x.com/0Karsa/status/1696421162442760380  1608136498242805762
1238  https://x.com/fingerroll23/status/169636332024...            292372739

             username
725       txtdariburu
731       txtdariburu
801       Popmama_com
982       Popmama_com
1141  PEMERHATIHKMSMT
1142  PEMERHATIHKMSMT
1237           0Karsa
1238     fingerroll23

In [ ]:
# Menghapus baris duplikat berdasarkan kolom 'full_text'
df4_cleaned = df4.drop_duplicates(subset=['full_text'])

In [ ]:
# Memeriksa duplikat berdasarkan kolom 'full_text'
duplicates = df4_cleaned[df4_cleaned.duplicated(subset=['full_text'], keep=False)]
print("Duplikat berdasarkan 'full_text':\n", duplicates)

Duplikat berdasarkan 'full_text':
 Empty DataFrame
Columns: [conversation_id_str, created_at, favorite_count, full_text, id_str, image_url, in_reply_to_screen_name, lang, location, quote_count, reply_count, retweet_count, tweet_url, user_id_str, username]
Index: []

In [ ]:
df4_cleaned.to_csv('cleaned_kdrt4.csv', index=False)

In [ ]:
#  drop semua kolom kecuali full_text dan username pada df_cleaned

df4_fix = df4_cleaned[['full_text', 'username']]

In [ ]:
df4_fix.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1494 entries, 0 to 1497
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   full_text  1494 non-null   object
 1   username   1494 non-null   object
dtypes: object(2)
memory usage: 35.0+ KB

In [ ]:
#  gabungkan data df1 dan df2 ke df baru

# Gabungkan df1 dan df2 menjadi df_baru
df_total_cleaned2 = pd.concat([df_total_cleaned, df4_fix], ignore_index=True)

# Tampilkan beberapa baris pertama dari df_baru
df_total_cleaned2.head()

                                           full_text    username
0                      @isbellaruby @ycbennette kdrt  prengutJJH
1  Menikah adalah hal yang baik. Konsekuensinya a...  ruangtahul
2  @SitiMelyanaaa pelaku kdrt ini keknya bisa dip...   XANOSHITA
3  @ngemtot @iamoneofwan Solusi tolol! Pantesan l...   ShinFa_04
4  @ngemtot Sewajarnya itu ambigu loh bocil norma...   ShinFa_04

In [ ]:
# Memeriksa apakah ada nilai NaN dalam kolom 'full_text'
nan_rows = df_total_cleaned2[df_total_cleaned2['full_text'].isna()]
print("Baris dengan nilai NaN di kolom 'full_text':\n", nan_rows)

Baris dengan nilai NaN di kolom 'full_text':
 Empty DataFrame
Columns: [full_text, username]
Index: []

In [ ]:
# Memeriksa duplikat berdasarkan kolom 'full_text'
duplicates = df_total_cleaned2[df_total_cleaned2.duplicated(subset=['full_text'], keep=False)]
print("Duplikat berdasarkan 'full_text':\n", duplicates)

Duplikat berdasarkan 'full_text':
 Empty DataFrame
Columns: [full_text, username]
Index: []

In [ ]:
# Menghapus baris duplikat berdasarkan kolom 'full_text'
df_total_cleaned2 = df_total_cleaned2.drop_duplicates(subset=['full_text'])

In [ ]:
df_total_cleaned2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4983 entries, 0 to 5742
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   full_text  4983 non-null   object
 1   username   4983 non-null   object
dtypes: object(2)
memory usage: 116.8+ KB

In [ ]:
df_total_cleaned2.to_csv('cleaned_kdrtTotal3.csv', index=False)

In [ ]:
df5 = pd.read_csv('kdrt (5).csv')

In [ ]:
df5.head()

,conversation_id_str,created_at,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username
0,1893369456664957336,Sat Feb 22 18:37:10 +0000 2025,0,pernah jd korban kdrt haha dipersulit + diulur...,1893369456664957336,NaN,NaN,in,NaN,0,1,0,https://x.com/dadskarma/status/189336945666495...,90573290,dadskarma
1,1893138573978919362,Sat Feb 22 17:11:39 +0000 2025,0,@Heraloebss Temenku bawa 2 batita dianter adek...,1893347936043426191,NaN,Heraloebss,in,"Kota Batam, Kepulauan Riau",0,0,0,https://x.com/aiiDAMN/status/1893347936043426191,414581663,aiiDAMN
2,1893298671497740559,Sat Feb 22 13:55:53 +0000 2025,0,miris bgt yaaaa indon tuh rill ga decent civil...,1893298671497740559,NaN,NaN,in,NaN,0,1,0,https://x.com/ceratoph_/status/189329867149774...,1558970121288564736,ceratoph_
3,1893266054895321376,Sat Feb 22 13:20:04 +0000 2025,0,@geprekalter gue lapor kdrt sendirian ke polse...,1893289655488979009,NaN,geprekalter,in,Indonesia,0,0,0,https://x.com/ch0choyule/status/18932896554889...,1006481777009963008,ch0choyule
4,1893274186266624390,Sat Feb 22 12:18:35 +0000 2025,26,&gt; Dijelasin kalo mau visum ntar prosedurnya...,1893274186266624390,NaN,NaN,in,indonesia,0,1,12,https://x.com/frierensaga/status/1893274186266...,1005123494470869003,frierensaga

In [ ]:
df5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 114 entries, 0 to 113
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   conversation_id_str      114 non-null    int64
 1   created_at               114 non-null    object
 2   favorite_count           114 non-null    int64
 3   full_text                114 non-null    object
 4   id_str                   114 non-null    int64
 5   image_url                6 non-null      object
 6   in_reply_to_screen_name  70 non-null     object
 7   lang                     114 non-null    object
 8   location                 65 non-null     object
 9   quote_count              114 non-null    int64
 10  reply_count              114 non-null    int64
 11  retweet_count            114 non-null    int64
 12  tweet_url                114 non-null    object
 13  user_id_str              114 non-null    int64
 14  username                 114 non-null    object
dtypes: int64(7), object(8)
memory usage: 13.5+ KB

In [ ]:
# Memeriksa apakah ada nilai NaN dalam kolom 'full_text'
nan_rows = df5[df5['full_text'].isna()]
print("Baris dengan nilai NaN di kolom 'full_text':\n", nan_rows)

Baris dengan nilai NaN di kolom 'full_text':
 Empty DataFrame
Columns: [conversation_id_str, created_at, favorite_count, full_text, id_str, image_url, in_reply_to_screen_name, lang, location, quote_count, reply_count, retweet_count, tweet_url, user_id_str, username]
Index: []

In [ ]:
# Memeriksa duplikat berdasarkan kolom 'full_text'
duplicates = df5[df5.duplicated(subset=['full_text'], keep=False)]
print("Duplikat berdasarkan 'full_text':\n", duplicates)

Duplikat berdasarkan 'full_text':
 Empty DataFrame
Columns: [conversation_id_str, created_at, favorite_count, full_text, id_str, image_url, in_reply_to_screen_name, lang, location, quote_count, reply_count, retweet_count, tweet_url, user_id_str, username]
Index: []

In [ ]:
df4_cleaned.to_csv('cleaned_kdrt4.csv', index=False)

In [ ]:
#  drop semua kolom kecuali full_text dan username pada df_cleaned

df5_fix = df5[['full_text', 'username']]

In [ ]:
df5_fix.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 114 entries, 0 to 113
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   full_text  114 non-null    object
 1   username   114 non-null    object
dtypes: object(2)
memory usage: 1.9+ KB

In [ ]:
#  gabungkan data df1 dan df2 ke df baru

# Gabungkan df1 dan df2 menjadi df_baru
df_total_cleaned3 = pd.concat([df_total_cleaned2, df5_fix], ignore_index=True)

# Tampilkan beberapa baris pertama dari df_baru
df_total_cleaned3.head()

                                           full_text    username
0                      @isbellaruby @ycbennette kdrt  prengutJJH
1  Menikah adalah hal yang baik. Konsekuensinya a...  ruangtahul
2  @SitiMelyanaaa pelaku kdrt ini keknya bisa dip...   XANOSHITA
3  @ngemtot @iamoneofwan Solusi tolol! Pantesan l...   ShinFa_04
4  @ngemtot Sewajarnya itu ambigu loh bocil norma...   ShinFa_04

In [ ]:
df_total_cleaned3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5097 entries, 0 to 5096
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   full_text  5097 non-null   object
 1   username   5097 non-null   object
dtypes: object(2)
memory usage: 79.8+ KB

In [ ]:
# Memeriksa apakah ada nilai NaN dalam kolom 'full_text'
nan_rows = df_total_cleaned3[df_total_cleaned3['full_text'].isna()]
print("Baris dengan nilai NaN di kolom 'full_text':\n", nan_rows)

Baris dengan nilai NaN di kolom 'full_text':
 Empty DataFrame
Columns: [full_text, username]
Index: []

In [ ]:
# Memeriksa duplikat berdasarkan kolom 'full_text'
duplicates = df_total_cleaned3[df_total_cleaned3.duplicated(subset=['full_text'], keep=False)]
print("Duplikat berdasarkan 'full_text':\n", duplicates)

Duplikat berdasarkan 'full_text':
                                               full_text      username
3084            Wkwkwk saya lapor kak seto kalau kdrt.   crewSEONGHWA
3085  @ayangmu_ Update kondisi pelaku kdrt. Hampir p...  dragsystemtt
3086  @ayangmu_ Buat kalian para istri kamu itu puny...  overlinesart
3087  @law20956 @Pakbhabin_id @PoldaMetro @ListyoSig...        rvviz7
3088  @Pakbhabin_id @PoldaMetro @ListyoSigitP @ahrie...      law20956
...                                                 ...           ...
5092  @HaubAkalam @txtmustikajaya @ZoneVenomWar Ini ...  PriaPemurung
5093  @detikcom Kek kasus seorang istri kena KDRT. U...   rahadyan999
5094  Benci banget sama orang2 kayak gitu. Giliran k...   beemydarlin
5095  @langilea8 @RidhaIntifadha Ya bnr perkara nnti...    stanza7777
5096  @Mata_Netizen62 @__AnakKolong @Anak__Ogi @LexW...   MujiAfianto

[196 rows x 2 columns]

In [ ]:
# Menghapus baris duplikat berdasarkan kolom 'full_text'
df_total_cleaned3 = df_total_cleaned3.drop_duplicates(subset=['full_text'])

In [ ]:
df_total_cleaned3.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4999 entries, 0 to 5057
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   full_text  4999 non-null   object
 1   username   4999 non-null   object
dtypes: object(2)
memory usage: 117.2+ KB

In [ ]:
df_total_cleaned3.to_csv('cleaned_kdrtTotal3.csv', index=False)

In [ ]:
df6 = pd.read_csv('kdrt (6).csv')

In [ ]:
df6.head()

,conversation_id_str,created_at,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username
0,1897344948237951389,Thu Mar 06 11:09:50 +0000 2025,0,@Kayyisaaaaaa klo kena kdrt hrus lapor,1897605538923655385,NaN,Kayyisaaaaaa,in,handle by admin,0,0,0,https://x.com/RlMBUN/status/1897605538923655385,878445572411097088,RlMBUN
1,1897054600685146483,Wed Mar 05 04:26:03 +0000 2025,0,@salsatrash Yg begini harus lapor kesiapa ya? ...,1897141533348126957,NaN,salsatrash,in,NaN,0,0,0,https://x.com/seazueka/status/1897141533348126957,1753264667760459776,seazueka
2,1897091861334118496,Wed Mar 05 01:08:40 +0000 2025,1,Bbrp tahun lalu temn ada yg jd korban kdrt lap...,1897091861334118496,NaN,NaN,in,"Busan, Republic of Korea",0,0,0,https://x.com/aimiyaura/status/189709186133411...,1389001568351969280,aimiyaura
3,1896324135044915233,Mon Mar 03 03:53:08 +0000 2025,3,@txtdrimedia Bukan Ngadu ke Polisi Warga Lapor...,1896408473484853609,NaN,txtdrimedia,in,iNews Tower,0,0,2,https://x.com/officialinews_/status/1896408473...,132078023,officialinews_
4,1896130299735724368,Sun Mar 02 09:55:26 +0000 2025,0,@maapgmain Kalau lapor polisi sertakan bukti K...,1896137262108401723,NaN,maapgmain,in,Tangerang,0,0,0,https://x.com/Fchou3333/status/189613726210840...,1661649279054921728,Fchou3333

In [ ]:
df6.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 210 entries, 0 to 209
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   conversation_id_str      210 non-null    int64
 1   created_at               210 non-null    object
 2   favorite_count           210 non-null    int64
 3   full_text                210 non-null    object
 4   id_str                   210 non-null    int64
 5   image_url                8 non-null      object
 6   in_reply_to_screen_name  140 non-null    object
 7   lang                     210 non-null    object
 8   location                 116 non-null    object
 9   quote_count              210 non-null    int64
 10  reply_count              210 non-null    int64
 11  retweet_count            210 non-null    int64
 12  tweet_url                210 non-null    object
 13  user_id_str              210 non-null    int64
 14  username                 210 non-null    object
dtypes: int64(7), object(8)
memory usage: 24.7+ KB

In [ ]:
# Memeriksa apakah ada nilai NaN dalam kolom 'full_text'
nan_rows = df6[df6['full_text'].isna()]
print("Baris dengan nilai NaN di kolom 'full_text':\n", nan_rows)

Baris dengan nilai NaN di kolom 'full_text':
 Empty DataFrame
Columns: [conversation_id_str, created_at, favorite_count, full_text, id_str, image_url, in_reply_to_screen_name, lang, location, quote_count, reply_count, retweet_count, tweet_url, user_id_str, username]
Index: []

In [ ]:
# Memeriksa duplikat berdasarkan kolom 'full_text'
duplicates = df6[df6.duplicated(subset=['full_text'], keep=False)]
print("Duplikat berdasarkan 'full_text':\n", duplicates)

Duplikat berdasarkan 'full_text':
     conversation_id_str                      created_at  favorite_count  \
3   1896324135044915233  Mon Mar 03 03:53:08 +0000 2025               3
5   1894268609100485063  Sun Mar 02 03:09:07 +0000 2025               0
21  1894268609100485063  Tue Feb 25 07:27:51 +0000 2025               4
36  1893499611161207010  Sun Feb 23 04:37:29 +0000 2025               8

                                            full_text               id_str  \
3   @txtdrimedia Bukan Ngadu ke Polisi Warga Lapor...  1896408473484853609
5   @Heraloebss Bukan Ngadu ke Polisi Warga Lapor ...  1896035009842331684
21  @Heraloebss Bukan Ngadu ke Polisi Warga Lapor ...  1894288183715930428
36  @txtdrimedia Bukan Ngadu ke Polisi Warga Lapor...  1893520534367060395

   image_url in_reply_to_screen_name lang     location  quote_count  \
3        NaN             txtdrimedia   in  iNews Tower            0
5        NaN              Heraloebss   in  iNews Tower            0
21       NaN              Heraloebss   in  iNews Tower            0
36       NaN             txtdrimedia   in  iNews Tower            0

    reply_count  retweet_count  \
3             0              2
5             0              0
21            0              1
36            1              0

                                            tweet_url  user_id_str  \
3   https://x.com/officialinews_/status/1896408473...    132078023
5   https://x.com/officialinews_/status/1896035009...    132078023
21  https://x.com/officialinews_/status/1894288183...    132078023
36  https://x.com/officialinews_/status/1893520534...    132078023

          username
3   officialinews_
5   officialinews_
21  officialinews_
36  officialinews_

In [ ]:
# Menghapus baris duplikat berdasarkan kolom 'full_text'
df6_cleaned = df6.drop_duplicates(subset=['full_text'])

In [ ]:
# Memeriksa duplikat berdasarkan kolom 'full_text'
duplicates = df6_cleaned[df6_cleaned.duplicated(subset=['full_text'], keep=False)]
print("Duplikat berdasarkan 'full_text':\n", duplicates)

Duplikat berdasarkan 'full_text':
 Empty DataFrame
Columns: [conversation_id_str, created_at, favorite_count, full_text, id_str, image_url, in_reply_to_screen_name, lang, location, quote_count, reply_count, retweet_count, tweet_url, user_id_str, username]
Index: []

In [ ]:
df4_cleaned.to_csv('cleaned_kdrt4.csv', index=False)

In [ ]:
#  drop semua kolom kecuali full_text dan username pada df_cleaned

df6_fix = df6_cleaned[['full_text', 'username']]

In [ ]:
df6_fix.info()

<class 'pandas.core.frame.DataFrame'>
Index: 208 entries, 0 to 209
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   full_text  208 non-null    object
 1   username   208 non-null    object
dtypes: object(2)
memory usage: 4.9+ KB

In [ ]:
#  gabungkan data df1 dan df2 ke df baru

# Gabungkan df1 dan df2 menjadi df_baru
df_total_cleaned4 = pd.concat([df_total_cleaned3, df6_fix], ignore_index=True)

# Tampilkan beberapa baris pertama dari df_baru
df_total_cleaned4.head()

                                           full_text    username
0                      @isbellaruby @ycbennette kdrt  prengutJJH
1  Menikah adalah hal yang baik. Konsekuensinya a...  ruangtahul
2  @SitiMelyanaaa pelaku kdrt ini keknya bisa dip...   XANOSHITA
3  @ngemtot @iamoneofwan Solusi tolol! Pantesan l...   ShinFa_04
4  @ngemtot Sewajarnya itu ambigu loh bocil norma...   ShinFa_04

In [ ]:
df_total_cleaned4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5207 entries, 0 to 5206
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   full_text  5207 non-null   object
 1   username   5207 non-null   object
dtypes: object(2)
memory usage: 81.5+ KB

In [ ]:
# Memeriksa apakah ada nilai NaN dalam kolom 'full_text'
nan_rows = df_total_cleaned4[df_total_cleaned4['full_text'].isna()]
print("Baris dengan nilai NaN di kolom 'full_text':\n", nan_rows)

Baris dengan nilai NaN di kolom 'full_text':
 Empty DataFrame
Columns: [full_text, username]
Index: []

In [ ]:
# Memeriksa duplikat berdasarkan kolom 'full_text'
duplicates = df_total_cleaned4[df_total_cleaned4.duplicated(subset=['full_text'], keep=False)]
print("Duplikat berdasarkan 'full_text':\n", duplicates)

Duplikat berdasarkan 'full_text':
                                               full_text         username
75          @dearchaniee TLONG BNTU LAPOR AKU KENA KDRT       mognahceah
122   Sumpah gue pengen cerita ini bener bener sanga...    Msmoon7343381
257   @ramydhia Biar gueh rangkum keluh kesah orang2...       LittleDucx
317   Ada istri korban kdrt suami lapor polisi sama ...         ireona29
440   TW// KDRT || Bantu Kawal Seorang Dokter di Nga...  bacottetangga__
...                                                 ...              ...
5202  @zoelfick Bangsatnya polisi kalo nerima lapora...        EldiRizky
5203  viralin aja nder terus lapor ke provos minta t...         citaboon
5204  @koyengggg99 @9Uy10j1gB2 @Dededarmamuh Ya emg ...          maeka31
5205  @Metro_TV Nah udah paling bener ini nerima sis...       pandAE86__
5206  Harusnya sbg pasangan yg sah dimata hukum &amp...    skysbluepiece

[342 rows x 2 columns]

In [ ]:
# Menghapus baris duplikat berdasarkan kolom 'full_text'
df_total_cleaned4 = df_total_cleaned4.drop_duplicates(subset=['full_text'])

In [ ]:
# Memeriksa duplikat berdasarkan kolom 'full_text'
duplicates = df_total_cleaned4[df_total_cleaned4.duplicated(subset=['full_text'], keep=False)]
print("Duplikat berdasarkan 'full_text':\n", duplicates)

Duplikat berdasarkan 'full_text':
 Empty DataFrame
Columns: [full_text, username]
Index: []

In [ ]:
df_total_cleaned4.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5036 entries, 0 to 5094
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   full_text  5036 non-null   object
 1   username   5036 non-null   object
dtypes: object(2)
memory usage: 118.0+ KB

In [ ]:
df_total_cleaned4.to_csv('cleaned_kdrtTotal4.csv', index=False)

In [ ]:
df = pd.read_csv('cleaned_kdrtBillar.csv')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4969 entries, 0 to 4968
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   conversation_id_str      4969 non-null   int64
 1   created_at               4969 non-null   object
 2   favorite_count           4969 non-null   int64
 3   full_text                4969 non-null   object
 4   id_str                   4969 non-null   int64
 5   image_url                763 non-null    object
 6   in_reply_to_screen_name  149 non-null    object
 7   lang                     4969 non-null   object
 8   location                 3555 non-null   object
 9   quote_count              4969 non-null   int64
 10  reply_count              4969 non-null   int64
 11  retweet_count            4969 non-null   int64
 12  tweet_url                4969 non-null   object
 13  user_id_str              4969 non-null   int64
 14  username                 4969 non-null   object
dtypes: int64(7), object(8)
memory usage: 582.4+ KB

In [ ]:
#  drop semua kolom kecuali full_text dan username pada df_cleaned

df_fix = df[['full_text', 'username']]

In [ ]:
df_fix.head()

                                           full_text         username
0  @bacottetangga__ Lesti Part 2 ? Kalau gatau ke...      RizkyBillar
1  @ozarangkuti Anagram dari bola biliar adalah r...      eericcyrill
2  oke guys mungkin banyak yang bakal bilang kasu...  claraaulia63094
3  Masih Ingat Kasus Rizky Billar yang Cekik dan ...        tvOneNews
4  @kegblgnunfaedh Udah selingkuh sama cewek lain...    ferry_krnwn16

In [ ]:
df_fix.tail()

                                              full_text        username
4964  Kronologi Lesty Kejora Diduga Jadi Korban KDRT...  cianjurekspres
4965  Sudah Anggap Lesti Kejora sebagai Anak Inul Da...       Gorajuara
4966  Diterpa Kabar KDRT Ramalan Mbak You Soal Rumah...  paragramberita
4967  Duh! Padahal Selalu Terlihat Mesra Lesti Kejor...       Gorajuara
4968  Heboh! Mbak You Pernah Meramal Nasib Lesti Seb...     fajaronline

In [ ]:
df_fix.to_csv('cleaned_kdrtBillarBersih.csv', index=False)

In [ ]:
df = pd.read_csv("stopkdrt.csv")

In [ ]:
#  drop semua kolom kecuali full_text dan username pada df_cleaned

df = df[['full_text', 'username']]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 435 entries, 0 to 434
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   full_text  435 non-null    object
 1   username   435 non-null    object
dtypes: object(2)
memory usage: 6.9+ KB

In [ ]:
# Memeriksa apakah ada nilai NaN dalam kolom 'full_text'
nan_rows = df[df['full_text'].isna()]
print("Baris dengan nilai NaN di kolom 'full_text':\n", nan_rows)

Baris dengan nilai NaN di kolom 'full_text':
 Empty DataFrame
Columns: [full_text, username]
Index: []

In [ ]:
# Memeriksa duplikat berdasarkan kolom 'full_text'
duplicates = df[df.duplicated(subset=['full_text'], keep=False)]
print("Duplikat berdasarkan 'full_text':\n", duplicates)

Duplikat berdasarkan 'full_text':
                                              full_text        username
16   Armor Toreador Divonis 4 5 Tahun Penjara atas ...  officialinews_
36   Armor Toreador Divonis 4 5 Tahun Penjara atas ...  officialinews_
254  BREAKING NEWS: Armor Toreador Suami Cut Intan ...    RyanRafael37
260  BREAKING NEWS: Armor Toreador Suami Cut Intan ...       rafmaull_

In [ ]:
# Menghapus baris duplikat berdasarkan kolom 'full_text'
df_cleaned = df.drop_duplicates(subset=['full_text'])

In [ ]:
# Memeriksa duplikat berdasarkan kolom 'full_text'
duplicates = df_cleaned[df_cleaned.duplicated(subset=['full_text'], keep=False)]
print("Duplikat berdasarkan 'full_text':\n", duplicates)

Duplikat berdasarkan 'full_text':
 Empty DataFrame
Columns: [full_text, username]
Index: []

In [ ]:
df_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
Index: 433 entries, 0 to 434
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   full_text  433 non-null    object
 1   username   433 non-null    object
dtypes: object(2)
memory usage: 10.1+ KB

In [ ]:
#  save file to csv

# Assuming df_cleaned is the DataFrame you want to save
df_cleaned.to_csv('cleaned_cutIntanKdrt.csv', index=False)